### ISSUE TITLE
production build process errors on mac

### ISSUE THREAD

**Issue by davegariepy** [ridereceipts/ridereceipts#16]
**Describe the bug**
build process errors out

**To Reproduce**
1. npm install
2. npm run build
3. last successful console output is:  
`rebuilding native production dependencies platform=darwin arch=x64`
4. first error line: 
`fsevents@1.2.4 install /Users/david/Develop/git/ridereceipts/node_modules/fsevents`

**Expected behavior**
expect to build production version on Mac

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14
 - node v9.5.0
 - npm 6.4.1
 - nvm 0.33.8

**Comment by mrgodhani** [comment]
@ddddave Your node would be the culprit. Try updating node to latest and rebuild it. Current version is v11. Also try to use `yarn`

**Comment by davegariepy** [comment]
Hey @mrgodhani, thanks for the quick reply!

I switched to node v11 and then tried yarn, but no dice.

The output:
```
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 0/1249(node:8473) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[-/5] ⡀ waiting...
[-/5] ⡀ waiting...
[3/5] ⡀ fsevents
[4/5] ⡀ electron
warning Error running install script for optional dependency: "/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments: 
Directory: /Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@11.0.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.0.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/davidgariepy/.node-gyp/11.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/davidgariepy/.node-gyp/11.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/davidgariepy/.node-gyp/11.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command \"/Users/davidgariepy/.nvm/versions/node/v11.0.0/bin/node\" \"/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--module=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64\" \"--napi_version=3\" \"--node_abi_napi=napi\" \"--python=/usr/bin/python\"
gyp ERR! cwd /Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/davidgariepy/.nvm/versions/node/v11.0.0/bin/node /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node --module_name=fse --module_path=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64 --napi_version=3 --node_abi_napi=napi --python=/usr/bin/python' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command \"/Users/davidgariepy/.nvm/versions/node/v11.0.0/bin/node\" \"/Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/davidgariepy/Develop/git/ridereceipts/node_modules/fsevents
node-pre-gyp ERR! node -v v11.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
[-/5] ⠠ waiting...
[-/5] ⠠ waiting...
[3/5] ⠠ fsevents
[4/5] ⠠ electron
error /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass
Output:
Building: /Users/davidgariepy/.nvm/versions/node/v11.0.0/bin/node /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/Users/davidgariepy/.nvm/versions/node/v11.0.0/bin/node',
gyp verb cli   '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@11.0.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/bin/python" in the PATH
gyp verb `which` succeeded /usr/bin/python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import sys; print "2.7.10
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 11.0.0
gyp verb command install [ '11.0.0' ]
gyp verb install input version string "11.0.0"
gyp verb install installing version: 11.0.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 11.0.0
gyp verb build dir attempting to create "build" dir: /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/davidgariepy/.node-gyp/11.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/davidgariepy/.node-gyp/11.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/davidgariepy/.node-gyp/11.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/Users/davidgariepy/.nvm/versions/node/v11.0.0/bin/node" "/Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/davidgariepy/Develop/git/ridereceipts/node_modules/node-sass
gyp ERR! node -v v11.0.0
```


Perhaps this has to do with my build environment? - I dont have xcode installed...

**Comment by mrgodhani** [comment]
@ddddave  It's complaining about Xcode. So yes you will need to install Xcode in your machine. Also your yarn seems outdated. Latest version of yarn is 1.10

**Comment by davegariepy** [comment]
I followed these instructions to setup for building electron and it worked: 

 https://electronjs.org/docs/development/build-instructions-macos#prerequisites

Thanks!

**Comment by mrgodhani** [comment]
Although remember I use https://github.com/electron-userland/electron-builder. So build commands are different as that package handles multi platform builds. For now Windows and Mac only.

**Comment by davegariepy** [comment]
ok thanks, still learning electron. Appreciate the help.
